### ISSUE TITLE
Possible install with nabucasa? 

### ISSUE THREAD

**Issue by Nik18111997** [iainbullock/tesla-http-proxy-docker#1]
Hi, I'd like to know if possible install this add on with nabucasa set up on home assistant istance ? Thanks

**Comment by iainbullock** [comment]
I don’t know sorry. I don’t use Nabucasa (NC) and don’t know the details of
how it works or what it can do.

Internet access to my Home Assistant (HA) instance (and all my locally
hosted services) is through Cloudflare. It’s free and well documented.

Having said that, it probably would work ok in parallel but outside of NC.
The docker version of the proxy is independent of HA so you can setup your
own webserver and use this docker. The webserver must be accessible from
the internet with full SSL certifications.

My advice is to get your webserver working, which depending upon your
experience of these things is a challenge in itself. I’ve used both
Cloudflare and DuckDNS / LetsEncrypt methods successfully for this. I’m not
supporting how to do this here as it’s well documented elsewhere.

We then need to wait for this PR
https://github.com/alandtse/tesla/pull/853
 to be resolved (and any mods to my project resulting from this) before it
will work nicely with HA.

Regards Iain

**Comment by Nik18111997** [comment]
Ah ok 👍 thank you, in the weekend I try to install duckdns and ngix for http add on, after report you if works

**Comment by iainbullock** [comment]
Just to be clear.

If you can use Home Assistant Add-ons then you should use the original
version of this
https://github.com/llamafilm/tesla-http-proxy-addon

Mine is for those who can’t or don’t want to use HA add ons.

Mine works but will be clunky with HA compared  to llamafilm’s. We await
the PR to be closed to see how it works out.

If you are going to use my version I suggest you install Nginx as a
standalone installation (or docker) not a HA addon.

Also note this webserver setup is nothing to do with Nginx reverse proxies.
There is a lot of confusion out there.

Cheers Iain

**Comment by Nik18111997** [comment]
Yes, sorry i don't write this, I try with another add on, thanks

**Comment by iainbullock** [comment]
This is getting some discussion on llamfilm's version https://github.com/llamafilm/tesla-http-proxy-addon/discussions/3
