### ISSUE TITLE
Details on setup

### ISSUE THREAD

**Issue by dasviridov** [iainbullock/tesla-http-proxy-docker#20]
Hi iainbullock,

Thanks a loot for this project. I really appreciate your work!

I've got it partially work with my setup but struggle to make it work beyond config.sh stage.
Container itself runs but gives following info in logs. 

```
-----
[02:43:20] main:INFO: *** Generating Partner Authentication Token ***
[02:43:21] main:ERROR: HTTP 400: Bad Request
Configuration options not set in /data/config.sh, exiting
Configuration options not set in /data/config.sh, exiting
Configuration Options are:
CLIENT_ID=<client_id>
CLIENT_SECRET=Not Shown
DOMAIN=<my_domain>
PROXY_HOST=<docker_app_name>
REGION=North America, Asia-Pacific
Setting up for first launch
Setting up GnuPG and password-store
/data/gnugpg/pubring.kbx
------------------------
pub   ed25519 2024-03-19 [SC] [expires: 2027-03-19]
      C507151D3.....
uid           [ultimate] myself
sub   cv25519 2024-03-19 [E]

created directory: '/data/password-store/'
Password store initialized for myself
Generating self-signed SSL certificate
Generating keypair
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZ.....==
-----END PUBLIC KEY-----
Starting temporary Python app for authentication flow. Delete /data/access_token to force regeneration in the future
Configuration Options are:
CLIENT_ID=<client_id>
CLIENT_SECRET=Not Shown
DOMAIN=<my_domain>
PROXY_HOST=<docker_app_name>
REGION=North America, Asia-Pacific
Public keys com.tesla.3p.public-key.pem or selfsigned.pem missing from /share
Generating self-signed SSL certificate
Generating keypair
-----BEGIN PUBLIC KEY-----
MFkwEwYHKo...==
-----END PUBLIC KEY-----
Starting temporary Python app for authentication flow. Delete /data/access_token to force regeneration in the future
```

So there must be something I am missing.

I've got Nginx Proxy Manager on my server and Cloudflare taking care of SSL. I set it up Nginx Proxy Manager to return com.tesla.3p.public-key.pem on that .wellknown path using FQDN. It works. Server returns file on https://<mydomain>/.well-known/appspecific/com.tesla.3p.public-key.pem.

I also route server to point to a docker app on 8099 port for root path. However just https://<mydomain> returns error. And if I try to open it locally using internal ip and either 443 or 8099 ports it returns nothing.

Could you please point me on what I am missing? I can help you with documentation if I get it to work.

Thank you!

**Comment by dasviridov** [comment]
Got it working! Finally.

Okay, the issue was in CLIENT_SECRET in config.sh. In my case the secret has $ in it, which is probably a special character in shell scripts. It needs to be in single quotes like REGION.

Once I added quotes and restarted container it all worked flawlessly, including HA setup.

I confirm this works  under Nginx Proxy Manager inside Unraid.

**Comment by iainbullock** [comment]
Thanks for this. I will update the dev branch and include in a future update
