### ISSUE TITLE
CLOUDFLARE.md assumes you are running HAOS which goes against the point of this project

### ISSUE THREAD

**Issue by chrismcneil** [iainbullock/tesla-http-proxy-docker#48]
I was trying to follow https://github.com/iainbullock/tesla-http-proxy-docker/blob/main/tesla_http_proxy/CLOUDFLARE.md but ran into issues right away as it is assuming you can run the nginx addon in HAOS. This sort of goes against the point of this project as it was created for people who are running home assistant in docker. Hopefully [@juchong](https://github.com/juchong) can help create a new version that uses strictly docker?

**Comment by iainbullock** [comment]
The guide was written by a contributor to describe their own setup. 

You don't need to use HAOS which as you say defeats the purpose of the project. 

My setup as author is based on everything running in its own independent docker container, i.e. Home Assistant; nginx; tesla-http-proxy-docker. 

If using Cloudflare (which I also do), then you can run cloudflared in it's own docker too.

Have a good at installing using the main instructions, and raise a new Issue here if you need any support

**Comment by iainbullock** [comment]
Sorry didn't mean to close - let me know if you have any further questions

**Comment by chrismcneil** [comment]
I was able to work out how to get everything running with parts of that doc and the blog post. I think it is all working but I am not able to get the HA integration working sadly. I have my docker compose setup a little differently and I think that is messing with the PROXY SSL CERTIFICATE location when I go to configure the integration. I am not seeing any logs though so I don't know why it is failing.

**Comment by chrismcneil** [comment]
Hmm seems my refresh token might not be working. 
`"error": "login_required", "error_description": "The refresh_token is invalid"`

**Comment by chrismcneil** [comment]
I ended up using https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613 to. generate a new refresh token and was able to get it working! Thanks for all the work on this project!

**Comment by iainbullock** [comment]
Glad you got it sorted, thanks for posting the update
