### ISSUE TITLE
Use this container withour nginx

### ISSUE THREAD

**Issue by carmelo42** [iainbullock/tesla-http-proxy-docker#49]
I wonder how to use this addon without nginx, but Traefik instead?

I have traefik running on my homelab, which provides several services (and all 80 / 443 call are served by this traefik reverse proxy).

So ... I can't use nginx, and I need to find a workaround.

Any help would be much appreciated :)

**Comment by iainbullock** [comment]
Someone asked a similar question an the parent project. It's not clear if it got resolved, but the thread does explain how nginx is used in this setup. It is both a proxy (which I think Traefik could do), but also a publically accessible webserver to serve up the com.tesla.3p.public-key.pem key. It doesn't have to nginx of course, but you need this functionaility in your setup. 

https://github.com/llamafilm/tesla-http-proxy-addon/issues/6

**Comment by iainbullock** [comment]
How did you get on?

**Comment by iainbullock** [comment]
Ok thanks for letting me know
