### ISSUE TITLE
Unable to share vehicle - Request timed out

### ISSUE THREAD

**Issue by devedse** [iainbullock/tesla-http-proxy-docker#57]
Hello everyone,

Just like everyone else I'm unique and want to have my very own specific setup to integrate my tesla into home assistant :smile:.

What I've got working for now is:
1. Running the container
1. Forwarding tesla.myowndevedsedomain.com to the `tesla-http-proxy-docker` container on port 8099 (Using NPM (Nginx Proxy Manager)) from my NPM host to a separate host running the container.
1. Completing steps 1 - 3:
![image](https://github.com/user-attachments/assets/4a73e0be-05d3-4abb-9c2f-64a1912e4a56)
1. However when I try to go through step 4, I run into the following issue on the mobile app (after clicking "Accept" when it asks me if I want to allow access to my Tesla)
![image](https://github.com/user-attachments/assets/ebbda95f-db84-4c4d-9331-86040b37c1ad)

On one hand I'd be interested in a direct solution for my problem. But I'd probably be able to figure this out if someone could help me understand where things are getting stuck.

* Is this somewhere in a connection from Tesla to me?
* Is this my public key not being correct?
* Etc..

I also checked my NPM logs (which with `tail -f *` show any request being made to my domain) but this only shows the following:

```
==> proxy-host-28_access.log <==
[******* +0000] - - 206 - GET https tesla.*****.******** "/.well-known/appspecific/com.tesla.3p.public-key.pem" [Client ************] [Length ******] [Gzip -] [Sent-to ************] "okhttp/4.11.0" "-"
```

**Comment by devedse** [comment]
So I retried things this morning and now it worked :).

One thing that confused me is what the "proxy url" configuration setting was being used for. But I now figured out this is because homeassistant needs to connect to the tesla http proxy over an HTTPS connection for which we need a self signed certificate.

Hence setting the proxy url to for example: `pi.deveinternal` will generate an HTTPS certificate for that url. You should also then forward `pi.deveinternal` in your DNS server (e.g. your ubiquiti router or your adguard/pihole) to the host that's running the tesla http proxy.

That way home assistant can securely connect (over https) to the tesla http proxy docker container.

I think it would be useful to add some background information on this in the tutorial (in like a hidden dropdown that people can click open) to explain why they are configuring things they are.

Anyways thanks for everything, it works now :).

**Comment by devedse** [comment]
Ok I've also solved that. Apparently somewhere in the process either a refresh token expired or I copied the wrong public key. Anyway, I've deleted everything in the http proxy data directory and then reran the steps. Now it works :smile:

**Comment by iainbullock** [comment]
Excellent thanks for sharing!
